#pragma once
#include <cmath>
#include <stdio.h>
#include <stdlib.h>
#include <chrono>
#include "sub/poly.h"
#include "sub/poly_eqs.h"
#include <random>
#include <inttypes.h>
#include <cuda_runtime.h>
#include "sub/cleartext_encoding_cpu.h"
#include "tests.cuh"